name: Send a Slack Message
author: Manuel Entrena
description: "Send a slack message with workflow information"
inputs:
  webhook_slack:
    description: "Slack Webhook"
    required: true
  message:
    description: "Slack Message"
    required: true
runs:
  using: docker
  image: "Dockerfile"
  args:
    - ${{ inputs.webhook_slack }}
    - ${{ inputs.message }}